FROM python:3.13-slim AS builder

WORKDIR /app

COPY requirements-worker.txt .
RUN pip install --no-cache-dir --prefix=/install --extra-index-url https://download.pytorch.org/whl/cpu torch && \
    pip install --no-cache-dir --prefix=/install -r requirements-worker.txt

FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY . .

EXPOSE 9000

CMD ["python", "worker.py"]
