FROM python:3.13-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-worker.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements-worker.txt

FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY worker.py .

EXPOSE 9000

CMD ["python", "worker.py"]
